// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251102061325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("backend.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Michael Hartl",
                            CreatedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An Introduction to Version Control with Git",
                            PublishedYear = 2016,
                            Title = "Learn Enough Git to Be Dangerous"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Keyvan Kambakhsh",
                            CreatedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A Colorful Introduction to Engineering!",
                            PublishedYear = 2024,
                            Title = "The Super Programmer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
